import { BoardObjectSchema, type BoardObject } from '@coboard/shared'
import { boardStore } from '../../stores/boardStore.js'

/**
 * Dev-only fixture loading.
 *
 * `?stress=1` loads fixtures/stress-board.json — the 10,000 objects PRD risk
 * R-2 requires committed from week 1, and the board every performance claim is
 * measured against (R-PERF-025). "It feels fast" on an empty board is not
 * evidence.
 *
 * Guarded by import.meta.env.DEV so the 5 MB fixture can never reach a
 * production bundle. The dynamic import keeps it out of the initial chunk even
 * in dev, so it does not distort the bundle-size gate.
 */

interface StressFixture {
  objects: unknown[]
}

export async function loadStressFixture(): Promise<number> {
  const res = await fetch('/fixtures/stress-board.json')
  if (!res.ok) throw new Error(`stress fixture: HTTP ${res.status}`)
  const data = (await res.json()) as StressFixture

  // Validate at the boundary — R-SEC-003. The fixture is generated by our own
  // script, but a malformed one should fail loudly here rather than produce a
  // NaN coordinate that blanks the canvas (R-SEC-004).
  const objects: BoardObject[] = []
  for (const raw of data.objects) {
    const parsed = BoardObjectSchema.safeParse(raw)
    if (parsed.success) objects.push(parsed.data)
  }

  boardStore.getState().loadObjects(objects)
  return objects.length
}

/** Reads dev query flags. Returns false in production regardless of the URL. */
export function devFlags(): { stress: boolean; debug: boolean } {
  if (!import.meta.env.DEV) return { stress: false, debug: false }
  const params = new URLSearchParams(window.location.search)
  return { stress: params.get('stress') === '1', debug: params.get('debug') === '1' }
}
